# Generated by Django 5.1 on 2024-08-25 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='images',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdImage',
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
    ]
