# Generated by Django 5.1.1 on 2024-09-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='logo',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
