# Generated by Django 5.1.1 on 2024-10-04 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exoplanet',
        ),
    ]
